spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  flyway:
    enabled: true
    baselineOnMigrate: true
    locations: classpath:db/migration/{vendor},classpath:db/seed/test # when you want to give test seed, add location test seed too

  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  kafka:
    producer:
      bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
      enable-auto-commit: false
    listener:
      ack-mode: manual

  redis:
    host: localhost
    port: 6379

app:
  topic:
    account:
      register-account-enterprise: register-account-enterprise
  jwt:
    access-token-valid-time: 3600 #Access token validity time in seconds (1 hours)
    refresh-token-valid-time: 1209600 #Refresh token validity time in seconds (2 weeks)
    secret-key: test-jwt-secret-key-test-jwt-secret-key
    payload:
      secret-key: test-jwt-payload-secret-key-test-jwt-payload-secret-key #AES256암호화 키는 32자리 이상
      iv: test-jwt-payload-iv #AES256 iv는 16자리 이상

  web-client:
    base-url: http://api.belloga.com # domain name